// =============
// AUTOGENERATED
// =============
// 
// Dependency Module Include File for @ModuleName@
#include <Gene2/Platform/PlatformInfo.hpp>

#if defined(G2_COMPILER_GNUC)
	#pragma GCC diagnostic push
	#pragma GCC system_header
#endif

@CMAKE_CONFIGURABLE_FILE_CONTENT@

#if defined(G2_COMPILER_GNUC)
	#pragma GCC diagnostic pop
#endif
