// Copyright 2017-2018 Barney Wilks. All Rights Reserved

#include <X11/keysymdef.h>
#include <X11/keysym.h>

enum class Keys
{
    NUM0 = XK_0,
    NUM1 = XK_1,
    NUM2 = XK_2,
    NUM3 = XK_3,
    NUM4 = XK_4,
    NUM5 = XK_5,
    NUM6 = XK_6,
    NUM7 = XK_7,
    NUM8 = XK_8,
    NUM9 = XK_9,
    A = XK_a,
    B = XK_b,
    C = XK_c,
    D = XK_d,
    E = XK_e,
    F = XK_f,
    G = XK_g,
    H = XK_h,
    I = XK_i,
    J = XK_j,
    K = XK_k,
    L = XK_l,
    M = XK_m,
    N = XK_n,
    O = XK_o,
    P = XK_p,
    Q = XK_q,
    R = XK_r,
    S = XK_s,
    T = XK_t,
    U = XK_u,
    V = XK_v,
    W = XK_w,
    X = XK_x,
    Y = XK_y,
    Z = XK_z,
    LeftArrow = XK_Left,
    RightArrow = XK_Right,
    UpArrow = XK_Up,
    DownArrow = XK_Down,
    F1 = XK_F1,
    F2 = XK_F2,
    F3 = XK_F3,
    F4 = XK_F4,
    F5 = XK_F5,
    F6 = XK_F6,
    F7 = XK_F7,
    F8 = XK_F8,
    F9 = XK_F9,
    F10 = XK_F10,
    F11 = XK_F11,
    Space = XK_space,
    Escape = XK_Escape
};
